### ISSUE TITLE
tangos serve isn't working with certain databases

### ISSUE THREAD

**Issue by anchwr** [pynbody/tangos#157]
I recently created a few databases and am getting an error when I run tangos serve with all but one of them. The merger tree display works fine with all of them, but as soon as I try to plot any other set of properties, the web server displays an error that links to a page that says "Internal Server Error. The server encountered an unexpected internal server error. (generated by waitress)". The error that shows up in the terminal window is
`Traceback (most recent call last):
  File "/Users/anna/anaconda3/envs/astroconda/lib/python3.7/site-packages/pyramid-2.0-py3.7.egg/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
   File "/Users/anna/anaconda3/envs/astroconda/lib/python3.7/site-packages/pyramid-2.0-py3.7.egg/pyramid/view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.`

I have forked tangos and have been using a custom handler for Enzo simulations processed with yt and rockstar to create my databases. However, my fork is up to date and both the databases that generate the error and the one that does not were made with the same handler. The only difference that I can think of is that the database that works is quite a bit smaller than the others (31 timesteps, compared to ~400).

**Comment by apontzen** [comment]
I am guessing this is probably to do with the naming of your databases  -- could you specify the names of the simulations and the timesteps so that I can confirm this? (Or even better, provide a sample database that reproduces the error.)

**Comment by anchwr** [comment]
Thanks for the quick response! I just uploaded one of the databases to google drive. Here's the link: https://drive.google.com/file/d/1hAUQ6uWmMwqwOeBiOR4xlQvB2eB4kHS9/view?usp=sharing

**Comment by apontzen** [comment]
There seem to be two related issues about generating valid URLs for this database. I've tried fixing them in pull request #158 - could you see if this fixes your issue?

**Comment by anchwr** [comment]
That works with all of my databases! Thank you so much!
