### ISSUE TITLE
Systematic database lock when importing first properties with MPI

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#180]
Hi,

I have been using the ability to `import properties` pre-calculated from halo finders. In serial mode, everything goes smoothly (but slowly) but I get a systematic "Database is locked" error when using the MPI mode. This only affects the very first batch of computations, the import then proceeds as normal without failing and I end up with all properties successfully imported except for 1/2 missing outputs from the first batch. The same behaviour has occurred with `Ramses+AdaptaHOP` and `Ramses+AHF`. 

My exact command is 
```mpirun -np 10 tangos import-properties --for $simname --backwards --backend mpi4py```

and the log reads
```
[  0] 2022-04-14 10:16:48,633 : Send job 0 of 236 to node 1
[  0] 2022-04-14 10:16:48,633 : Send job 1 of 236 to node 2
[  0] 2022-04-14 10:16:48,633 : Send job 2 of 236 to node 3
[  0] 2022-04-14 10:16:48,633 : Send job 3 of 236 to node 4
[  0] 2022-04-14 10:16:48,633 : Send job 4 of 236 to node 5
[  0] 2022-04-14 10:16:48,633 : Send job 5 of 236 to node 6
[  0] 2022-04-14 10:16:48,633 : Send job 6 of 236 to node 7
[  0] 2022-04-14 10:16:48,633 : Send job 7 of 236 to node 8
[  0] 2022-04-14 10:16:48,633 : Send job 8 of 236 to node 9
[  5] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00237' z=0.01 t=13.74 Gyr>
[  6] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00236' z=0.01 t=13.71 Gyr>
[  2] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00240' z=0.00 t=13.83 Gyr>
[  3] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00239' z=0.00 t=13.80 Gyr>
[  1] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00241' z=-0.00 t=13.84 Gyr>
[  4] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00238' z=0.00 t=13.79 Gyr>
[  9] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00233' z=0.01 t=13.65 Gyr>
[  7] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00235' z=0.01 t=13.70 Gyr>
[  8] 2022-04-14 10:16:48,633 : Processing <TimeStep 'halo685x09/output_00234' z=0.01 t=13.69 Gyr>
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
/home/mrey/.local/lib/python3.8/site-packages/pynbody-1.1.0-py3.8-linux-x86_64.egg/pynbody/snapshot/ramses.py:811: UserWarning: Using field 'tform' to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher.
  warnings.warn("Using field %s to distinguish stars. If this is wrong, try editing your config.ini, section [ramses], entry particle-distinguisher."%pb_name)
pynbody.halo : An error occurred while reading substructure, aborting
[  8] 2022-04-14 10:17:58,756 : Add 225663 properties
[  5] 2022-04-14 10:18:00,213 : Add 223211 properties
[  7] 2022-04-14 10:18:04,466 : Add 224071 properties
[  6] 2022-04-14 10:18:04,719 : Add 224742 properties
[  3] 2022-04-14 10:18:09,259 : Add 227631 properties
[  4] 2022-04-14 10:18:10,924 : Add 226091 properties
[  1] 2022-04-14 10:18:13,422 : Add 233113 properties
[  2] 2022-04-14 10:18:19,651 : Add 230700 properties
[  0] 2022-04-14 10:18:30,116 : Send job 9 of 236 to node 8
[  8] 2022-04-14 10:18:30,116 : Processing <TimeStep 'halo685x09/output_00232' z=0.01 t=13.62 Gyr>
[  9] 2022-04-14 10:18:36,937 : Add 226532 properties
[  0] 2022-04-14 10:18:42,793 : Send job 10 of 236 to node 5
[  5] 2022-04-14 10:18:42,793 : Processing <TimeStep 'halo685x09/output_00231' z=0.02 t=13.61 Gyr>
[  0] 2022-04-14 10:18:54,909 : Send job 11 of 236 to node 6
[  6] 2022-04-14 10:18:54,909 : Processing <TimeStep 'halo685x09/output_00230' z=0.02 t=13.56 Gyr>
Traceback (most recent call last):
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mrey/.local/bin/tangos", line 11, in <module>
    load_entry_point('tangos', 'console_scripts', 'tangos')()
  File "/home/mrey/tangos/tangos/scripts/__init__.py", line 48, in main
    args.func(args)
  File "/home/mrey/tangos/tangos/tools/__init__.py", line 54, in run
    parallel_tasks.launch(obj.run_calculation_loop, 2, [])
  File "/home/mrey/tangos/tangos/parallel_tasks/__init__.py", line 54, in launch
    backend.launch(_exec_function_or_server, num_procs, [function, args])
  File "/home/mrey/tangos/tangos/parallel_tasks/backends/mpi4py.py", line 61, in launch
    function(*args)
  File "/home/mrey/tangos/tangos/parallel_tasks/__init__.py", line 86, in _exec_function_or_server
    function(*args)
  File "/home/mrey/tangos/tangos/tools/property_importer.py", line 122, in run_calculation_loop
    self._import_properties_for_timestep(ts, names, object_typetag)
  File "/home/mrey/tangos/tangos/tools/property_importer.py", line 104, in _import_properties_for_timestep
    self._session.commit()
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1431, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/mrey/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO halolink (halo_from_id, halo_to_id, weight, creator_id, relation_id) VALUES (?, ?, ?, ?, ?)]
[parameters: (677303, 677303, 1.0, 16, 76)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
[  0] 2022-04-14 10:19:07,331 : Send job 12 of 236 to node 4
[  4] 2022-04-14 10:19:07,331 : Processing <TimeStep 'halo685x09/output_00229' z=0.02 t=13.54 Gyr>
....
....
```

Any ideas on what could be causing this and how to fix it?

**Comment by apontzen** [comment]
Yes it looks like there is no protection against this with SQLite. 

It is fairly likely this would be fixed very straight-forwardly at line 103 by adding a lock, something like

```python
logger.info("Add %d properties", len(rows_to_store))
with parallel_tasks.ExclusiveLock("add_properties"):
        self._session.add_all(rows_to_store)
        self._session.commit()
```

**Comment by Martin-Rey** [comment]
Thanks for the quick input, this indeed fixes the issue as far as I can tell. Will submit through a separate PR
