### ISSUE TITLE
python3.6 pyramid_debugtoolbar

### ISSUE THREAD

**Issue by TobiBu** [pynbody/tangos#6]
Hi, 

I finally played around with the database. Creating and filling works fine.
However, the web interface seems not to work for me under python3.6 the error below is what I get if I type 
`pserve development.ini`

in the subfolder web.

> 2017-12-07 00:13:26,752 INFO  [sqlalchemy.engine.base.Engine:1243][MainThread] SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2017-12-07 00:13:26,753 INFO  [sqlalchemy.engine.base.Engine:1244][MainThread] ()
2017-12-07 00:13:26,755 INFO  [sqlalchemy.engine.base.Engine:1243][MainThread] SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2017-12-07 00:13:26,755 INFO  [sqlalchemy.engine.base.Engine:1244][MainThread] ()
2017-12-07 00:13:26,756 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("dictionary")
2017-12-07 00:13:26,756 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,758 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("creators")
2017-12-07 00:13:26,758 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,758 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("simulations")
2017-12-07 00:13:26,758 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,759 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("simulationproperties")
2017-12-07 00:13:26,759 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,759 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("trackdata")
2017-12-07 00:13:26,759 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,759 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("timesteps")
2017-12-07 00:13:26,759 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,760 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("halos")
2017-12-07 00:13:26,760 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,760 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("haloproperties")
2017-12-07 00:13:26,760 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,760 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("halolink")
2017-12-07 00:13:26,760 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
2017-12-07 00:13:26,761 INFO  [sqlalchemy.engine.base.Engine:1140][MainThread] PRAGMA table_info("arrayplotoptions")
2017-12-07 00:13:26,761 INFO  [sqlalchemy.engine.base.Engine:1143][MainThread] ()
Traceback (most recent call last):
  File "/Users/buck/anaconda3/bin/pserve", line 6, in <module>
    sys.exit(main())
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/Users/buck/.local/lib/python3.6/site-packages/PasteDeploy-1.5.2-py3.6.egg/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/buck/.local/lib/python3.6/site-packages/PasteDeploy-1.5.2-py3.6.egg/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/Users/buck/.local/lib/python3.6/site-packages/PasteDeploy-1.5.2-py3.6.egg/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/Users/buck/.local/lib/python3.6/site-packages/PasteDeploy-1.5.2-py3.6.egg/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/Users/buck/.local/lib/python3.6/site-packages/PasteDeploy-1.5.2-py3.6.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/buck/.local/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/web/__init__.py", line 8, in main
    config = Configurator(settings=settings)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/config/__init__.py", line 301, in __init__
    exceptionresponse_view=exceptionresponse_view,
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/config/__init__.py", line 412, in setup_registry
    self.include(inc)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/config/__init__.py", line 727, in include
    c = self.maybe_dotted(callable)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/config/__init__.py", line 825, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/path.py", line 320, in maybe_resolve
    return self._resolve(dotted, package)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/path.py", line 327, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid-1.5.7-py3.6.egg/pyramid/path.py", line 376, in _zope_dottedname_style
    found = __import__(used)
ModuleNotFoundError: No module named 'pyramid_debugtoolbar'<

any suggestions?

cheers
Tobias

**Comment by apontzen** [comment]
I think setup.py must be missing a bunch of dependencies.  @mtremmel had a similar issue. For some reason I never saw it. What python distribution are you using?

**Comment by TobiBu** [comment]
I use the anaconda3 python distribution

**Comment by TobiBu** [comment]
Hi,
now I get this error: 

>   File "/Users/buck/.local/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/web/views/halo_data.py", line 9, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'<

and google says StringIO is gone in python3 one should use `from io import StingIO`, however, the halo_data.py file in line 9 says `from six import StringIO` which, if I understand right should alleviate problems with python2 and python3 compatibility.

any further suggestions?

**Comment by apontzen** [comment]
Yes, it should be importing from six which should be fine. Did the new version definitely fully install? I am wondering if there is an old version that python is somehow seeing.

**Comment by TobiBu** [comment]
I removed the tangos folder in 

> /Users/buck/.local/lib/python3.6/site-packages/<

and reinstalled. Same problem.

**Comment by TobiBu** [comment]
sorry my mistake... I should read messages more carefully, there was indeed an old version under the anaconda folder.

It works now.

Thanks for your help

**Comment by TobiBu** [comment]
now the web server displays fine and the merger tree shows up, however plotting doesn't work. This error shows up:

> 2017-12-09 20:23:13,159 ERROR [pyramid_debugtoolbar:267][waitress] Uncaught Exception at http://localhost:6543/tutorial_changa/pioneer50h128.1536gst1.bwK1.000960/2/Mvir/vs/t().png?type=cascade&&object_typetag=halo
traceback url: http://localhost:6543/_debug_toolbar/34353339323636363634/exception
Traceback (most recent call last):
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/view.py", line 731, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_debugtoolbar-4.3-py3.6.egg/pyramid_debugtoolbar/toolbar.py", line 247, in toolbar_tween
    response = _handler(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_debugtoolbar-4.3-py3.6.egg/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
    result = handler(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_tm-2.2-py3.6.egg/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_tm-2.2-py3.6.egg/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_tm-2.2-py3.6.egg/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/view.py", line 617, in _call_view
    response = view_callable(context, request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 409, in viewresult_to_response
    result = view(context, request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/web/views/halo_data.py", line 195, in cascade_plot
    return finish(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/web/views/halo_data.py", line 138, in finish
    buffer = StringIO.StringIO()
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'<

**Comment by apontzen** [comment]
Oops! Try again now

**Comment by TobiBu** [comment]
Hi, plotting now works. However, displaying either the uvi image or gas maps doesn't work. Error message attached.

> 2017-12-11 13:44:48,373 INFO  [sqlalchemy.engine.base.Engine:1143][waitress] (31890,)
2017-12-11 13:44:48,505 INFO  [sqlalchemy.engine.base.Engine:699][waitress] ROLLBACK
2017-12-11 13:44:48,508 ERROR [pyramid_debugtoolbar:267][waitress] Uncaught Exception at http://localhost:6543/tutorial_changa/pioneer50h128.1536gst1.bwK1.000960/1/uvi_image.png
traceback url: http://localhost:6543/_debug_toolbar/313132323338313635333532/exception
Traceback (most recent call last):
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/tweens.py", line 12, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/view.py", line 731, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_debugtoolbar-4.3-py3.6.egg/pyramid_debugtoolbar/toolbar.py", line 247, in toolbar_tween
    response = _handler(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_debugtoolbar-4.3-py3.6.egg/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
    result = handler(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_tm-2.2-py3.6.egg/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_tm-2.2-py3.6.egg/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid_tm-2.2-py3.6.egg/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/view.py", line 617, in _call_view
    response = view_callable(context, request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 409, in viewresult_to_response
    result = view(context, request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/web/views/halo_data.py", line 236, in array_plot
    val, property_info = halo.calculate(name, True)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/halo.py", line 114, in calculate
    (value,), description = calculation.values_sanitized_and_description([self])
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/live_calculation/__init__.py", line 129, in values_sanitized_and_description
    values, desc = self.values_and_description(halos)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/live_calculation/__init__.py", line 583, in values_and_description
    values = self.values(halos)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/live_calculation/__init__.py", line 578, in values
    ret[0,i]=self._extraction_pattern.get_from_cache(h, self._name_id)[0]
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/extraction_patterns.py", line 65, in get_from_cache
    return self._postprocess(return_vals)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/extraction_patterns.py", line 111, in _postprocess
    return [o.get_data_with_reassembly_options() for o in outputs]
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/extraction_patterns.py", line 111, in <listcomp>
    return [o.get_data_with_reassembly_options() for o in outputs]
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/halo_data/property.py", line 78, in get_data_with_reassembly_options
    return self.data_raw
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/halo_data/property.py", line 63, in data_raw
    return data_attribute_mapper.get_data_of_unknown_type(self)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/data_attribute_mapper.py", line 25, in get_data_of_unknown_type
    return mapper.get(obj)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/data_attribute_mapper.py", line 112, in get
    return self.unpack(getattr(db_object, self._attribute_name))
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/data_attribute_mapper.py", line 173, in unpack
    return self._unpack_compressed(packed)
  File "/Users/buck/anaconda3/lib/python3.6/site-packages/tangos-1.0.dev0-py3.6.egg/tangos/core/data_attribute_mapper.py", line 161, in _unpack_compressed
    return pickle_loads(zlib.decompress(packed[2:]))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 43819: ordinal not in range(128)<

**Comment by apontzen** [comment]
Oh dear - please try again now. Thanks for uncovering all these issues!
