### ISSUE TITLE
Tangos breaking with python 3.7

### ISSUE THREAD

**Issue by Martin-Rey** [pynbody/tangos#89]
Hi,

Similarly to (https://github.com/pynbody/pynbody/issues/498), I found myself with failing unit tests for TANGOS and python 3.7.

Specifically, the tests failing are test_consistent_trees, test_gadget_rockstar, test_load_timestep, test_load_halo, test_tracking and test_yt.

An example error trace for the yt test follows:
```
======================================================================
ERROR: test suite for <module 'test_yt' from '/home/ucapmre/tangos/tests/test_yt.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/ucapmre/anaconda3/lib/python3.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/ucapmre/tangos/tests/test_yt.py", line 15, in setup
    add.SimulationAdderUpdater(output_manager).scan_simulation_and_add_all_descendants()
  File "/home/ucapmre/tangos/tangos/tools/add_simulation.py", line 40, in scan_simulation_and_add_all_descendants
    self.add_objects_to_timestep(ts, core.halo.Group)
  File "/home/ucapmre/tangos/tangos/tools/add_simulation.py", line 99, in add_objects_to_timestep
    min_halo_particles=self.min_halo_particles):
  File "/home/ucapmre/tangos/tangos/tools/add_simulation.py", line 86, in adapted
    for result in enumerate_fn(*args, **kwargs):
RuntimeError: generator raised StopIteration
``` 

It is hard to know whether some of these errors comes intrinsically from pynbody or from Tangos, because Tangos also relies on StopIteration for the enumerate_objects method of handlers:
https://github.com/pynbody/tangos/blob/7f36946b6b0aeee4d0031d2d9fa9248788409bc1/tangos/input_handlers/pynbody.py#L212-L223

This behavior seems to have changed in python 3.7 (https://www.python.org/dev/peps/pep-0479/) and now generates a proper RuntimeError, likely the cause of these crashes.

Hope this is clear
Martin

**Comment by Martin-Rey** [comment]
Fixed by #90
